##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

stages:

  Version:
    actions:
      - type: shell
        command: liquibase --version

  Validation:
    actions: 
      - type: liquibase
        command: validate

  Connect:
    actions:
      - type: liquibase
        command: connect

  History_Before_Rollback:
    actions:
      - type: liquibase
        command: history

  Rollback:
    actions:
      - type: liquibase
        command: rollback-one-update
        cmdArgs: {force: true}

## The endStage ALWAYS RUNS. 
## So put actions here which you desire to perform whether previous stages' actions succeed or fail.
## If you do not want any actions to ALWAYS RUN, simply delete the endStage from your flow file.

endStage:
  actions:
    - type: liquibase
      command: history
