# url: aws-secrets,liquibase-workshop-secret,dev_url
# username: aws-secrets,rds!cluster-4edf2350-6934-4a5b-9ffa-fc90f4229db2,username
# password: aws-secrets,rds!cluster-4edf2350-6934-4a5b-9ffa-fc90f4229db2,password
# liquibase.reports.enabled: false
# changelog-file: sqlcode/changelog.yaml
# liquibase.logLevel: INFO
